#!/bin/zsh -x

setopt EXTENDED_GLOB

pandoc --from markdown\
       --to latex\
       --listings\
       --number-sections\
       --filter=pandoc-autocomplete-caption\
       --filter=pandoc-fignos\
       --filter=pandoc-include\
       --filter=pandoc-minted\
       --latex-engine=lualatex\
       --include-in-header=`dirname $0`/../share/pppset/article.sty\
       --variable='documentclass:ltjarticle'\
       --variable='geometry:margin=1cm'\
       --output=${1:r}.tex\
       $1 &&
    lualatex\
        --draftmode\
        --interaction=nonstopmode\
        --shell-escape\
        ${1:r}.tex\
    &&\
    lualatex\
        --interaction=nonstopmode\
        --shell-escape\
        ${1:r}.tex ${1:r}.^*(log|md|pdf|tex)*
