#!/bin/zsh -x

pandoc\
    --from markdown\
    --to latex\
    --table-of-contents\
    --filter=pandoc-fignos\
    --filter=pandoc-autocomplete-caption\
    --filter=pandoc-include\
    --filter=pandoc-minted\
    --latex-engine=lualatex\
    --template=`dirname $0`/../share/pppset/article.sty\
    --variable='documentclass:ltjarticle'\
    --output=${1:r}.tex\
    $@\
    &&\
    lualatex\
        --draftmode\
        --interaction=nonstopmode\
        --shell-escape\
        ${1:r}.tex\
    &&\
    lualatex\
        --interaction=nonstopmode\
        --shell-escape\
        ${1:r}.tex ${1:r}.[^(log|md|pdf|tex)]*
